sudo: false
language: java
jdk: oraclejdk7
cache:
  directories:
    - '$HOME/.m2/repository'

script:
       - cd core && mvn clean install -Pcoverage
       - cd ../examples && mvn clean package
       - cd ../jpa && mvn clean package
