sudo: false
language: java
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
  - secure: NQYOSqeGA/2QpuUa7U4cpt27T26Ho2aeeUOIM2qAOXupQHY+20W9XwSYX5QfGKNacTms/G1TP4GqmhzUWKrmuXDFt2kCnvvhgXYAxj07uncj3e8Ifwi0p+kpxKt21F1uC5t6wRK6NWE8mCZl9ux/vY+6zwt0mQej6M2stNEwyNpIm6FXurtjlr7S2vJySBoz/0R9XdesC/1nXeIav5Up3ul/CNt9ns05n5NQ6/iSCj/ReEYld7KJ8cJEBz/byghp1cMizJoWa3eiVEGdaAPsIwRbFP8EO1OpfnX5G6TCPWefVITusGYxHbw7RZibtnNZCj+kacaiZpsIJmCkFcEeTiizQa/Q5ImfplChA0sd8QMlEZdLSQkaEqzHLEG+MtPyuPvYnESIdEXJwKAwmCP3sN5uTZKNweE0pKzT9VSqUW1YffK+mK1w8ytTVnDsES0KDInHnskdBO8pdjFEP28XWchW5o5z8rJfMUhe3R+YdbZ0K2Nq4XsLzWoTLxjcx/Ul8PWmbC0Dmkq+wjKjMtDSw6uxEGCeOrYDShAm2Fzz2h6aEmYIz/o3ap7JDDdsNODty7lD4vMmUATefCYpihZ25rKWMBkDrTYtHUl5P0qtp1otlbvr/bbp7MOQCVZhgu+eo9i1FSyDKC7wA3Lu90UaqKK2lvK9PZuG7F65TSDHbck=
  - secure: t8orU2UCBOixF5feLQipVswzFTF/QANKjl8NW0uxOuRbJhVedrAqvdXQuWsyQMm1WF/5PoRB2VUQT3jY2OCY5rbc6FMt0V34HAPkj4ybDjPu9g6m2bcIn3B7d8w8B3PgecFQ5VjrS8Skv//Ae4Eh2hVno9fuh+3g/0Muxg/9hYECuOIGpwuGjcUGRfc/mh7EGT7Qn/9KapkqNW7+HgPukCRIN7nmnGzRWxfDvXB8buT08nyKxTX+pE0b1iMvS8x4VZxN5KSmbnbXIrNyh5DsVU7whOiTjeV/gkHlgAA0oq+Zt/7E3r2DwmxoAx0ouLBKyug+CduLG8k1sPHbIrMF1Ca9P/BdTR1LfK5IQMm48+ttLbUo/i59Ao5V2ykLxfhbiRNehF71+WbsjoIiXmvvf9/Do/OLsJ+Fl7KpkO9vB5ZIxh/rnWUrz2Fk3RdxNkSYw3/gkjDdNCdTESvhxSJlD3AuybSnh9QJghwqpsrKiQzdljASnYV5GByqWoajNuiXUOTxhQWpZrB6hWj8IQCeQ6dSOCxD/GFf7fnbklfy8XZmlECCvS6bpE8yenbTQeJ/7DSZMTGnvd+Rwo/mjrA12AEJ2tKJFl3BxsuMLpmCBCRzt8lKEOfyh9VGx6pMJilMmDvaysYjvo14MmKyLEU9ezqx+azMjRZVds1+Lzs1UQ4=
script:
- mvn clean install jacoco:report coveralls:report -Pcoverage
- cd cdi && mvn -q cukedoctor:execute scm-publish:publish-scm -Pdocs
